/* tslint:disable */
/* eslint-disable */
/**
 * BarsantiExplorer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'deletedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'text'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    'tripId'?: number;
    /**
     * 
     * @type {Trip}
     * @memberof Comment
     */
    'trip'?: Trip;
}
/**
 * 
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'title'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProblemDetails
     */
    'status'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'detail'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'instance'?: string | null;
}
/**
 * 
 * @export
 * @interface Trip
 */
export interface Trip {
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'deletedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'image'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'address'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    'latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    'longitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    'geoHash'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    'typeId'?: number;
    /**
     * 
     * @type {TripType}
     * @memberof Trip
     */
    'tripType'?: TripType;
}
/**
 * 
 * @export
 * @interface TripResponse
 */
export interface TripResponse {
    /**
     * 
     * @type {number}
     * @memberof TripResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TripResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TripResponse
     */
    'deletedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripResponse
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripResponse
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripResponse
     */
    'image'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripResponse
     */
    'address'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TripResponse
     */
    'latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof TripResponse
     */
    'longitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof TripResponse
     */
    'geoHash'?: string | null;
    /**
     * 
     * @type {TripType}
     * @memberof TripResponse
     */
    'tripType'?: TripType;
}
/**
 * 
 * @export
 * @interface TripType
 */
export interface TripType {
    /**
     * 
     * @type {number}
     * @memberof TripType
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TripType
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TripType
     */
    'deletedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripType
     */
    'name'?: string | null;
}

/**
 * CommentsApi - axios parameter creator
 * @export
 */
export const CommentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get filtered comments
         * @param {string} [tripTitle] 
         * @param {string} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCommentsGet: async (tripTitle?: string, sort?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/comments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tripTitle !== undefined) {
                localVarQueryParameter['TripTitle'] = tripTitle;
            }

            if (sort !== undefined) {
                localVarQueryParameter['Sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a comment
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCommentsIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiCommentsIdDelete', 'id', id)
            const localVarPath = `/api/comments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a comment
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCommentsIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiCommentsIdGet', 'id', id)
            const localVarPath = `/api/comments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommentsApi - functional programming interface
 * @export
 */
export const CommentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get filtered comments
         * @param {string} [tripTitle] 
         * @param {string} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCommentsGet(tripTitle?: string, sort?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Comment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCommentsGet(tripTitle, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.apiCommentsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a comment
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCommentsIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCommentsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.apiCommentsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a comment
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCommentsIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TripResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCommentsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.apiCommentsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CommentsApi - factory interface
 * @export
 */
export const CommentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommentsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get filtered comments
         * @param {string} [tripTitle] 
         * @param {string} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCommentsGet(tripTitle?: string, sort?: string, options?: any): AxiosPromise<Array<Comment>> {
            return localVarFp.apiCommentsGet(tripTitle, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a comment
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCommentsIdDelete(id: number, options?: any): AxiosPromise<boolean> {
            return localVarFp.apiCommentsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a comment
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCommentsIdGet(id: number, options?: any): AxiosPromise<TripResponse> {
            return localVarFp.apiCommentsIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CommentsApi - object-oriented interface
 * @export
 * @class CommentsApi
 * @extends {BaseAPI}
 */
export class CommentsApi extends BaseAPI {
    /**
     * 
     * @summary Get filtered comments
     * @param {string} [tripTitle] 
     * @param {string} [sort] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public apiCommentsGet(tripTitle?: string, sort?: string, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).apiCommentsGet(tripTitle, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a comment
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public apiCommentsIdDelete(id: number, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).apiCommentsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a comment
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public apiCommentsIdGet(id: number, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).apiCommentsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TripsApi - axios parameter creator
 * @export
 */
export const TripsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get filtered trips
         * @param {number} [tripType] 
         * @param {string} [search] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {number} [geoHashPrecision] 
         * @param {boolean} [includeDeleted] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsGet: async (tripType?: number, search?: string, sort?: string, order?: string, page?: number, limit?: number, latitude?: number, longitude?: number, geoHashPrecision?: number, includeDeleted?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/trips`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tripType !== undefined) {
                localVarQueryParameter['TripType'] = tripType;
            }

            if (search !== undefined) {
                localVarQueryParameter['Search'] = search;
            }

            if (sort !== undefined) {
                localVarQueryParameter['Sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['Order'] = order;
            }

            if (page !== undefined) {
                localVarQueryParameter['Page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['Limit'] = limit;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['Latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['Longitude'] = longitude;
            }

            if (geoHashPrecision !== undefined) {
                localVarQueryParameter['GeoHashPrecision'] = geoHashPrecision;
            }

            if (includeDeleted !== undefined) {
                localVarQueryParameter['IncludeDeleted'] = includeDeleted;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a trip
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiTripsIdDelete', 'id', id)
            const localVarPath = `/api/trips/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a trip
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiTripsIdGet', 'id', id)
            const localVarPath = `/api/trips/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary update a trip
         * @param {number} id 
         * @param {File} [image] 
         * @param {string} [title] 
         * @param {string} [description] 
         * @param {string} [address] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {number} [typeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsIdPut: async (id: number, image?: File, title?: string, description?: string, address?: string, latitude?: number, longitude?: number, typeId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiTripsIdPut', 'id', id)
            const localVarPath = `/api/trips/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (image !== undefined) { 
                localVarFormParams.append('Image', image as any);
            }
    
            if (title !== undefined) { 
                localVarFormParams.append('Title', title as any);
            }
    
            if (description !== undefined) { 
                localVarFormParams.append('Description', description as any);
            }
    
            if (address !== undefined) { 
                localVarFormParams.append('Address', address as any);
            }
    
            if (latitude !== undefined) { 
                localVarFormParams.append('Latitude', latitude as any);
            }
    
            if (longitude !== undefined) { 
                localVarFormParams.append('Longitude', longitude as any);
            }
    
            if (typeId !== undefined) { 
                localVarFormParams.append('TypeId', typeId as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new trip
         * @param {File} image 
         * @param {string} title 
         * @param {string} description 
         * @param {string} address 
         * @param {number} latitude 
         * @param {number} longitude 
         * @param {number} [typeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsPost: async (image: File, title: string, description: string, address: string, latitude: number, longitude: number, typeId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'image' is not null or undefined
            assertParamExists('apiTripsPost', 'image', image)
            // verify required parameter 'title' is not null or undefined
            assertParamExists('apiTripsPost', 'title', title)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('apiTripsPost', 'description', description)
            // verify required parameter 'address' is not null or undefined
            assertParamExists('apiTripsPost', 'address', address)
            // verify required parameter 'latitude' is not null or undefined
            assertParamExists('apiTripsPost', 'latitude', latitude)
            // verify required parameter 'longitude' is not null or undefined
            assertParamExists('apiTripsPost', 'longitude', longitude)
            const localVarPath = `/api/trips`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (image !== undefined) { 
                localVarFormParams.append('Image', image as any);
            }
    
            if (title !== undefined) { 
                localVarFormParams.append('Title', title as any);
            }
    
            if (description !== undefined) { 
                localVarFormParams.append('Description', description as any);
            }
    
            if (address !== undefined) { 
                localVarFormParams.append('Address', address as any);
            }
    
            if (latitude !== undefined) { 
                localVarFormParams.append('Latitude', latitude as any);
            }
    
            if (longitude !== undefined) { 
                localVarFormParams.append('Longitude', longitude as any);
            }
    
            if (typeId !== undefined) { 
                localVarFormParams.append('TypeId', typeId as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TripsApi - functional programming interface
 * @export
 */
export const TripsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TripsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get filtered trips
         * @param {number} [tripType] 
         * @param {string} [search] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {number} [geoHashPrecision] 
         * @param {boolean} [includeDeleted] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTripsGet(tripType?: number, search?: string, sort?: string, order?: string, page?: number, limit?: number, latitude?: number, longitude?: number, geoHashPrecision?: number, includeDeleted?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Trip>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTripsGet(tripType, search, sort, order, page, limit, latitude, longitude, geoHashPrecision, includeDeleted, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TripsApi.apiTripsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a trip
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTripsIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTripsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TripsApi.apiTripsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a trip
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTripsIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TripResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTripsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TripsApi.apiTripsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary update a trip
         * @param {number} id 
         * @param {File} [image] 
         * @param {string} [title] 
         * @param {string} [description] 
         * @param {string} [address] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {number} [typeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTripsIdPut(id: number, image?: File, title?: string, description?: string, address?: string, latitude?: number, longitude?: number, typeId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TripResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTripsIdPut(id, image, title, description, address, latitude, longitude, typeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TripsApi.apiTripsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new trip
         * @param {File} image 
         * @param {string} title 
         * @param {string} description 
         * @param {string} address 
         * @param {number} latitude 
         * @param {number} longitude 
         * @param {number} [typeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTripsPost(image: File, title: string, description: string, address: string, latitude: number, longitude: number, typeId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TripResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTripsPost(image, title, description, address, latitude, longitude, typeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TripsApi.apiTripsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TripsApi - factory interface
 * @export
 */
export const TripsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TripsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get filtered trips
         * @param {number} [tripType] 
         * @param {string} [search] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {number} [geoHashPrecision] 
         * @param {boolean} [includeDeleted] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsGet(tripType?: number, search?: string, sort?: string, order?: string, page?: number, limit?: number, latitude?: number, longitude?: number, geoHashPrecision?: number, includeDeleted?: boolean, options?: any): AxiosPromise<Array<Trip>> {
            return localVarFp.apiTripsGet(tripType, search, sort, order, page, limit, latitude, longitude, geoHashPrecision, includeDeleted, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a trip
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsIdDelete(id: number, options?: any): AxiosPromise<boolean> {
            return localVarFp.apiTripsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a trip
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsIdGet(id: number, options?: any): AxiosPromise<TripResponse> {
            return localVarFp.apiTripsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary update a trip
         * @param {number} id 
         * @param {File} [image] 
         * @param {string} [title] 
         * @param {string} [description] 
         * @param {string} [address] 
         * @param {number} [latitude] 
         * @param {number} [longitude] 
         * @param {number} [typeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsIdPut(id: number, image?: File, title?: string, description?: string, address?: string, latitude?: number, longitude?: number, typeId?: number, options?: any): AxiosPromise<TripResponse> {
            return localVarFp.apiTripsIdPut(id, image, title, description, address, latitude, longitude, typeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new trip
         * @param {File} image 
         * @param {string} title 
         * @param {string} description 
         * @param {string} address 
         * @param {number} latitude 
         * @param {number} longitude 
         * @param {number} [typeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTripsPost(image: File, title: string, description: string, address: string, latitude: number, longitude: number, typeId?: number, options?: any): AxiosPromise<TripResponse> {
            return localVarFp.apiTripsPost(image, title, description, address, latitude, longitude, typeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TripsApi - object-oriented interface
 * @export
 * @class TripsApi
 * @extends {BaseAPI}
 */
export class TripsApi extends BaseAPI {
    /**
     * 
     * @summary Get filtered trips
     * @param {number} [tripType] 
     * @param {string} [search] 
     * @param {string} [sort] 
     * @param {string} [order] 
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {number} [latitude] 
     * @param {number} [longitude] 
     * @param {number} [geoHashPrecision] 
     * @param {boolean} [includeDeleted] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TripsApi
     */
    public apiTripsGet(tripType?: number, search?: string, sort?: string, order?: string, page?: number, limit?: number, latitude?: number, longitude?: number, geoHashPrecision?: number, includeDeleted?: boolean, options?: RawAxiosRequestConfig) {
        return TripsApiFp(this.configuration).apiTripsGet(tripType, search, sort, order, page, limit, latitude, longitude, geoHashPrecision, includeDeleted, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a trip
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TripsApi
     */
    public apiTripsIdDelete(id: number, options?: RawAxiosRequestConfig) {
        return TripsApiFp(this.configuration).apiTripsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a trip
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TripsApi
     */
    public apiTripsIdGet(id: number, options?: RawAxiosRequestConfig) {
        return TripsApiFp(this.configuration).apiTripsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary update a trip
     * @param {number} id 
     * @param {File} [image] 
     * @param {string} [title] 
     * @param {string} [description] 
     * @param {string} [address] 
     * @param {number} [latitude] 
     * @param {number} [longitude] 
     * @param {number} [typeId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TripsApi
     */
    public apiTripsIdPut(id: number, image?: File, title?: string, description?: string, address?: string, latitude?: number, longitude?: number, typeId?: number, options?: RawAxiosRequestConfig) {
        return TripsApiFp(this.configuration).apiTripsIdPut(id, image, title, description, address, latitude, longitude, typeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new trip
     * @param {File} image 
     * @param {string} title 
     * @param {string} description 
     * @param {string} address 
     * @param {number} latitude 
     * @param {number} longitude 
     * @param {number} [typeId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TripsApi
     */
    public apiTripsPost(image: File, title: string, description: string, address: string, latitude: number, longitude: number, typeId?: number, options?: RawAxiosRequestConfig) {
        return TripsApiFp(this.configuration).apiTripsPost(image, title, description, address, latitude, longitude, typeId, options).then((request) => request(this.axios, this.basePath));
    }
}



